package part5;

public class ExceptionExample {

	public static void main(String[] args) {
		System.out.println("Programe is started");
		System.out.println("Programe is progress");
		
//		ArithmeticException
		
//		int a =100;
//		try {
//		System.out.println(a/0);
//		} catch(ArithmeticException e) {
//		e.printStackTrace();
//		}
		

//		NullPointerException
		
//		String s = null;
//		try {
//		System.out.println(s.length());
//		}catch (NullPointerException e) {
//			e.printStackTrace();
//		}
		
		
		
	
//		NumberFormatException
		
//		String x = "abc";
//		int i = Integer.parseInt(x);
//		
		
//		ArrayIndexOutOfBoundsException
//		int arr[] = new int [5];
//		arr[10]= 100;
//		
		
		System.out.println("Programe is compiler");
		System.out.println("Programe is exited");

	}

}
